### ISSUE TITLE
Weird app behavior

### ISSUE THREAD

**Issue by LordInfernius** [MarkusMaal/BlueScreenSimulatorPlus#6] opened 2024-04-19 11:23 UTC
When I try to use Beep.SYS as the potential culprit file for the blue screen I get OrangeScreen Exception. I tried deleting settings.cfg, but it still doesn't work. Also, when I try to set the culprit file to Null.SYS, most text in the app's window is replaced with "undefined".

**Comment by MarkusMaal** [comment] 2024-04-19 12:53
The Null.SYS thing is intended behaviour. If you don't want to see undefined strings, try unchecking **Enable easter eggs** under **Settings > Simulator settings** and it shouldn't happen anymore.

I was able to reproduce the OrangeScreen Exception with Beep.SYS under the Windows 2000 simulator and it appears to be a bug. Working on a fix for version 2.13.

**Comment by MarkusMaal** [comment] 2024-04-19 14:31
Fixed on version 2.13

**Closed by MarkusMaal** 2024-04-19 14:31 UTC
Labels: bug
